import {
  Anchor,
  Award,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  Car,
  ChartColumn,
  ChartLine,
  ChartNoAxesCombined,
  ChartPie,
  CircleCheck,
  ClipboardCheck,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  CreditCard,
  Database,
  DollarSign,
  Dumbbell,
  FileText,
  Flag,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Handshake,
  Headphones,
  Heart,
  HeartHandshake,
  House,
  Key,
  Landmark,
  Layers,
  Leaf,
  Lightbulb,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Monitor,
  Mountain,
  Network,
  Package,
  Palette,
  PenTool,
  Phone,
  Plane,
  Presentation,
  Puzzle,
  Rocket,
  Scale,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Target,
  Timer,
  TrendingUp,
  Trophy,
  Truck,
  User,
  Users,
  Utensils,
  Video,
  Wallet,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

// The curated icons editors can pick (IconField). Content stores the key only, never a component
// or SVG. Add an icon: import it from lucide-react and add an entry (key, label, keywords).

type IconEntry = { icon: LucideIcon; label: string; keywords?: string };

export const ICONS = {
  // Used in docs/design
  "chart-growth": {
    icon: ChartNoAxesCombined,
    label: "Growth chart",
    keywords: "strategy analytics",
  },
  landmark: { icon: Landmark, label: "Bank", keywords: "finance institution" },
  megaphone: { icon: Megaphone, label: "Megaphone", keywords: "marketing brand announce" },
  users: { icon: Users, label: "People", keywords: "team culture group" },
  "shield-check": { icon: ShieldCheck, label: "Shield with check", keywords: "risk security safe" },
  sparkles: { icon: Sparkles, label: "Sparkles", keywords: "digital new magic" },
  target: { icon: Target, label: "Target", keywords: "focus goal aim" },
  handshake: { icon: Handshake, label: "Handshake", keywords: "partnership deal agreement" },
  lightbulb: { icon: Lightbulb, label: "Light bulb", keywords: "idea innovation perspective" },
  "trending-up": { icon: TrendingUp, label: "Trending up", keywords: "progress growth" },
  // Business and services
  briefcase: { icon: Briefcase, label: "Briefcase", keywords: "business work" },
  building: { icon: Building2, label: "Building", keywords: "office company" },
  "chart-line": { icon: ChartLine, label: "Line chart", keywords: "data results" },
  "chart-bar": { icon: ChartColumn, label: "Bar chart", keywords: "data report" },
  "chart-pie": { icon: ChartPie, label: "Pie chart", keywords: "share budget" },
  presentation: { icon: Presentation, label: "Presentation", keywords: "training workshop" },
  compass: { icon: Compass, label: "Compass", keywords: "direction guidance" },
  rocket: { icon: Rocket, label: "Rocket", keywords: "launch startup" },
  puzzle: { icon: Puzzle, label: "Puzzle", keywords: "solution integration" },
  layers: { icon: Layers, label: "Layers", keywords: "stack product" },
  network: { icon: Network, label: "Network", keywords: "connections structure" },
  scale: { icon: Scale, label: "Scale", keywords: "legal balance law" },
  "clipboard-check": { icon: ClipboardCheck, label: "Checklist", keywords: "audit compliance" },
  "circle-check": { icon: CircleCheck, label: "Check", keywords: "done quality" },
  award: { icon: Award, label: "Award", keywords: "quality badge" },
  trophy: { icon: Trophy, label: "Trophy", keywords: "win success" },
  star: { icon: Star, label: "Star", keywords: "favorite rating" },
  gem: { icon: Gem, label: "Gem", keywords: "premium value" },
  flag: { icon: Flag, label: "Flag", keywords: "milestone mission" },
  mountain: { icon: Mountain, label: "Mountain", keywords: "challenge vision" },
  anchor: { icon: Anchor, label: "Anchor", keywords: "stable trust" },
  // Money
  wallet: { icon: Wallet, label: "Wallet", keywords: "money finance" },
  "credit-card": { icon: CreditCard, label: "Credit card", keywords: "payment" },
  dollar: { icon: DollarSign, label: "Dollar", keywords: "money price" },
  // Tech and creative
  monitor: { icon: Monitor, label: "Monitor", keywords: "computer web" },
  code: { icon: Code, label: "Code", keywords: "development software" },
  cloud: { icon: Cloud, label: "Cloud", keywords: "hosting saas" },
  database: { icon: Database, label: "Database", keywords: "data storage" },
  lock: { icon: Lock, label: "Lock", keywords: "security privacy" },
  shield: { icon: Shield, label: "Shield", keywords: "protection" },
  key: { icon: Key, label: "Key", keywords: "access" },
  zap: { icon: Zap, label: "Lightning", keywords: "fast energy" },
  settings: { icon: Settings, label: "Settings", keywords: "operations process" },
  wrench: { icon: Wrench, label: "Wrench", keywords: "repair maintenance" },
  hammer: { icon: Hammer, label: "Hammer", keywords: "build construction" },
  palette: { icon: Palette, label: "Palette", keywords: "design creative" },
  "pen-tool": { icon: PenTool, label: "Pen tool", keywords: "design brand" },
  camera: { icon: Camera, label: "Camera", keywords: "photo" },
  video: { icon: Video, label: "Video", keywords: "film" },
  // People and care
  user: { icon: User, label: "Person", keywords: "client profile" },
  heart: { icon: Heart, label: "Heart", keywords: "care love" },
  "heart-handshake": {
    icon: HeartHandshake,
    label: "Caring handshake",
    keywords: "support community",
  },
  smile: { icon: Smile, label: "Smile", keywords: "happy satisfaction" },
  "graduation-cap": {
    icon: GraduationCap,
    label: "Graduation cap",
    keywords: "education learning",
  },
  "book-open": { icon: BookOpen, label: "Book", keywords: "learning resources" },
  stethoscope: { icon: Stethoscope, label: "Stethoscope", keywords: "health medical" },
  dumbbell: { icon: Dumbbell, label: "Dumbbell", keywords: "fitness" },
  leaf: { icon: Leaf, label: "Leaf", keywords: "sustainability nature" },
  // Places, contact, time
  house: { icon: House, label: "House", keywords: "home real estate" },
  store: { icon: Store, label: "Store", keywords: "shop retail" },
  "shopping-bag": { icon: ShoppingBag, label: "Shopping bag", keywords: "shop" },
  package: { icon: Package, label: "Package", keywords: "product delivery" },
  truck: { icon: Truck, label: "Truck", keywords: "shipping logistics" },
  car: { icon: Car, label: "Car", keywords: "automotive" },
  plane: { icon: Plane, label: "Plane", keywords: "travel" },
  utensils: { icon: Utensils, label: "Utensils", keywords: "food restaurant" },
  coffee: { icon: Coffee, label: "Coffee", keywords: "cafe meeting" },
  globe: { icon: Globe, label: "Globe", keywords: "world international web" },
  "map-pin": { icon: MapPin, label: "Map pin", keywords: "location" },
  mail: { icon: Mail, label: "Mail", keywords: "email contact" },
  phone: { icon: Phone, label: "Phone", keywords: "call contact" },
  "message-circle": { icon: MessageCircle, label: "Chat", keywords: "message support" },
  headphones: { icon: Headphones, label: "Headphones", keywords: "support audio" },
  calendar: { icon: Calendar, label: "Calendar", keywords: "booking schedule" },
  clock: { icon: Clock, label: "Clock", keywords: "time hours" },
  timer: { icon: Timer, label: "Timer", keywords: "speed" },
  "file-text": { icon: FileText, label: "Document", keywords: "report" },
  search: { icon: Search, label: "Search", keywords: "research discover" },
  gift: { icon: Gift, label: "Gift", keywords: "offer" },
} as const satisfies Record<string, IconEntry>;

export type IconKey = keyof typeof ICONS;

export const ICON_KEYS = Object.keys(ICONS) as [IconKey, ...IconKey[]];

export function isIconKey(value: unknown): value is IconKey {
  return typeof value === "string" && value in ICONS;
}
